---
- name: Configure multipath
  template:
    src: multipath.conf.j2
    dest: /etc/multipath.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart multipathd service
  systemd:
    name: multipathd
    state: restarted