---
- name: Install required packages
  become: yes
  yum:
    name:
      - iscsi-initiator-utils
      - device-mapper-multipath
    state: present

- name: Enable and start iSCSI initiator service
  become: yes
  systemd:
    name: iscsid
    enabled: yes
    state: started

- name: Enable and start multipathd service
  become: yes
  systemd:
    name: multipathd
    enabled: yes
    state: started
